// api/invoices.js
// GET  /api/invoices               -> list invoices (dashboard: draft/pending/overdue/paid)
// POST /api/invoices               -> create a new invoice + its line items

import { supabaseAdmin } from '../lib/supabaseAdmin.js';

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method === 'GET') {
    const { data, error } = await supabaseAdmin
      .from('invoices')
      .select(`
        id, invoice_no, invoice_date, due_date, status,
        subtotal, service_fee, vat_rate, vat_amount, total_amount,
        paid_date, paid_amount, payment_method, note,
        customers ( id, name_th, tax_id )
      `)
      .order('created_at', { ascending: false });

    if (error) return res.status(500).json({ error: error.message });
    return res.status(200).json({ invoices: data });
  }

  if (req.method === 'POST') {
    const { customerId, creditTermDays, subtotal, serviceFee, vatRate, note, items } = req.body || {};

    if (!customerId) return res.status(400).json({ error: 'customerId is required' });
    if (!Array.isArray(items) || items.length === 0) {
      return res.status(400).json({ error: 'At least one line item is required' });
    }

    // invoice_no is auto-generated by generate_invoice_no() (DB default) — don't set it here.
    const { data: invoice, error: invErr } = await supabaseAdmin
      .from('invoices')
      .insert([{
        customer_id: customerId,
        credit_term_days: creditTermDays || 0,
        subtotal: subtotal || 0,
        service_fee: serviceFee || 0,
        vat_rate: vatRate || 0,
        note: note || null,
        status: 'draft',
      }])
      .select()
      .single();

    if (invErr) return res.status(500).json({ error: invErr.message });

    const itemRows = items.map((it, idx) => ({
      invoice_id: invoice.id,
      line_no: idx + 1,
      service_type: it.serviceType,       // airline_ticket | airline_date_change | hotel | travel_insurance | service_fee | other
      description: it.description,
      airline: it.airline || null,
      flight_no: it.flightNo || null,
      route_from: it.routeFrom || null,
      route_to: it.routeTo || null,
      travel_date: it.travelDate || null,
      return_date: it.returnDate || null,
      return_flight_no: it.returnFlightNo || null,
      return_route_from: it.returnRouteFrom || null,
      return_route_to: it.returnRouteTo || null,
      ticket_no: it.ticketNo || null,
      policy_no: it.policyNo || null,
      insurance_plan: it.insurancePlan || null,
      coverage_start: it.coverageStart || null,
      coverage_end: it.coverageEnd || null,
      hotel_name: it.hotelName || null,
      check_in: it.checkIn || null,
      check_out: it.checkOut || null,
      room_type: it.roomType || null,
      num_rooms: it.numRooms || null,
      num_nights: it.numNights || null,
      passengers: it.passengers || null,
      unit_price: it.unitPrice || 0,
      quantity: it.quantity || 1,
      item_vat_rate: it.itemVatRate || 0,
    }));

    const { error: itemsErr } = await supabaseAdmin.from('invoice_items').insert(itemRows);

    if (itemsErr) {
      // Roll back the invoice header so we don't leave an orphaned draft with no items.
      await supabaseAdmin.from('invoices').delete().eq('id', invoice.id);
      return res.status(500).json({ error: itemsErr.message });
    }

    return res.status(201).json({ invoice });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
