// api/receipts.js
// GET  /api/receipts               -> list issued receipts (newest first)
// POST /api/receipts               -> issue a receipt against a paid/pending invoice
//
// receipt_no is auto-generated by the DB (generate_receipt_no() default),
// same pattern as invoice_no on the invoices table.

import { supabaseAdmin } from '../lib/supabaseAdmin.js';

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method === 'GET') {
    const { data, error } = await supabaseAdmin
      .from('receipts')
      .select(`
        id, receipt_no, receipt_date, amount, payment_method, note, created_at,
        invoices ( id, invoice_no, customers ( name_th ) )
      `)
      .order('created_at', { ascending: false });

    if (error) return res.status(500).json({ error: error.message });
    return res.status(200).json({ receipts: data });
  }

  if (req.method === 'POST') {
    const { invoiceId, paymentId, receiptDate, amount, paymentMethod, note } = req.body || {};

    if (!invoiceId) return res.status(400).json({ error: 'invoiceId is required' });
    if (!amount || amount <= 0) return res.status(400).json({ error: 'amount must be greater than 0' });

    const { data: receipt, error } = await supabaseAdmin
      .from('receipts')
      .insert([{
        invoice_id: invoiceId,
        payment_id: paymentId || null,
        receipt_date: receiptDate || new Date().toISOString().split('T')[0],
        amount,
        payment_method: paymentMethod || null,
        note: note || null,
      }])
      .select(`id, receipt_no, receipt_date, amount, payment_method, note, invoices ( id, invoice_no, customers ( name_th ) )`)
      .single();

    if (error) return res.status(500).json({ error: error.message });
    return res.status(201).json({ receipt });
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
